name: CI(PhpStan -> PhpUnit)

on:
  pull_request:

jobs:
  php-tests:
    if: (!contains(github.event.head_commit.message, '[skip ci]'))
    strategy:
      matrix:
        os: [ubuntu-24.04]
        php: [8.1, 8.2, 8.3]
        laravel: [10.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*

    runs-on: ${{ matrix.os }}

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, pdo_sqlite
          coverage: none
      - run: composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
      - run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Static analysis
        run: vendor/bin/phpstan --memory-limit=512M analyze

      - name: Migrate phpunit schema
        run: vendor/bin/phpunit --migrate-configuration

      - name: Unit testing
        run: vendor/bin/phpunit
