name: CI(PhpStan -> PhpUnit)

on:
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 0 * * *'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    if: (!contains(github.event.head_commit.message, '[skip ci]'))
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          memory_limit: 512M
          configuration: ./phpstan.neon

  php-tests:
    if: (!contains(github.event.head_commit.message, '[skip ci]'))
    needs: [phpstan]
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.0, 7.4]
        laravel: [7.*, 8.*, 9.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 9.*
            testbench: 7.*
          - laravel: 8.*
            testbench: 6.23
          - laravel: 7.*
            testbench: 5.*
        exclude:
          - laravel: 9.*
            php: 7.4
          # https://bytexd.com/fix-laravel-return-type-of-illuminatesupportcollectionoffsetexistskey/
          - laravel: 7.*
            php: 8.1

    runs-on: ${{ matrix.os }}

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, pdo_sqlite
          coverage: none
      - run: composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
      - run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
      - run: vendor/bin/phpunit
