name: Semantic Release Flow

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Semantic Release Flow
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        semantic-version: [17.3.9]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - run: npx semantic-release@18
