name: Semantic Release Flow

on:
  push:
    branches:
      - main
      - dev
      - next

jobs:
  semantic-release:
    name: Semantic Release Flow
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        semantic-version: [17.3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CREATE_RELEASE }}
          fetch-depth: 0
      - run: npm install -g '@limetech/semantic-release-laravel' --no-package-lock --silent
      - uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: ${{ matrix.semantic-version }}
          extends: '@limetech/semantic-release-laravel'
          branches: |
            [
              "main",
              {"name": "dev", "prerelease": true},
              {"name": "next", "prerelease": true},
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE }}
          GH_USERNAME: lime-ci
          GH_TOKEN: ${{ secrets.CREATE_RELEASE }}

      - run: curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=lime-technologies&apiToken=${{ secrets.PACKAGIST_TOKEN }}' -d'{"repository":{"url":"https://packagist.org/packages/lundalogik/laravel-newsletter-driver"}}'
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}