name: Run Tests - Older

on: [push, pull_request]

jobs:
  unit-tests:
    if: (!contains(github.event.head_commit.message, '[skip ci]'))
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [7.4]
        laravel: [5.*, 7.*]
        dependency-version: [prefer-stable]
        include:
          - laravel: 5.*
            testbench: 3.*
          - laravel: 7.*
            testbench: 5.*

    runs-on: ${{ matrix.os }}

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json
          coverage: none

      - name: Set composer options
        run: composer config --no-plugins allow-plugins.kylekatarnls/update-helper true

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: run phpunit
        run: vendor/bin/phpunit
